services:
  database:
    image: postgres:17.3
    container_name: database
    restart: unless-stopped
    tty: true
    profiles: [ db, server ]
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=rudo
    volumes:
      - ./database-data:/var/lib/postgresql/data
      - ./pg_hba.conf:/etc/pg_hba.conf
    command: [ '-c', 'hba_file=/etc/pg_hba.conf' ]
    healthcheck:
      test: [ 'CMD', 'pg_isready -h localhost -U postgres' ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    cpu_count: 2
    networks:
      rudo-network:
        ipv4_address: 10.5.0.2

  migrations:
    image: ghcr.io/emilpriver/geni:v1.1.5
    pull_policy: never
    restart: unless-stopped
    container_name: migrations
    profiles: [ db, server ]
    networks:
      rudo-network:
        ipv4_address: 10.5.0.10
    volumes:
      - ./migrations:/migrations
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@database:5432/rudo
    command: [ "up" ]
    depends_on:
      - database

  server:
    image: localhost/charlieroth/rudo:latest
    pull_policy: never
    container_name: server
    profiles: [ server ]
    ports:
      - "8080:8080"
    healthcheck:
      test: [ 'CMD-SHELL', 'wget -qO- http://localhost:8080/liveness || exit 1' ]
      interval: 5s
      timeout: 5s
      retries: 2
      start_period: 2s
    cpu_count: 2
    environment:
      - RUDO_PORT=8080
      - RUDO_DB_USER=postgres
      - RUDO_DB_PASSWORD=postgres
      - RUDO_DB_PORT=5432
      - RUDO_DB_NAME=rudo
      - RUDO_DB_HOST=database
      - RUDO_DB_DISABLE_TLS=true
    expose:
      - "8080:8080"
    networks:
      rudo-network:
        ipv4_address: 10.5.0.5
    depends_on:
      - migrations

volumes:
  database: {}

networks:
  rudo-network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/24
